version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    environment:
      - FLASK_ENV=development

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
